/*******************************************************************************
 * Copyright (c) 2012 Profactor GmbH
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Michael Hofmann
 *     - initial API and implementation and/or initial documentation
 *******************************************************************************/

//!!!autogenerated code - DO NOT EDIT!!!
 extern const CStringDictionary::TStringId g_nStringIdAtuador_Pistao;
 extern const CStringDictionary::TStringId g_nStringIdAvanco_Atuador;
 extern const CStringDictionary::TStringId g_nStringIdBOOL;
 extern const CStringDictionary::TStringId g_nStringIdCNF;
 extern const CStringDictionary::TStringId g_nStringIdINIT;
 extern const CStringDictionary::TStringId g_nStringIdINITO;
 extern const CStringDictionary::TStringId g_nStringIdPeca_inicio_esteira;
 extern const CStringDictionary::TStringId g_nStringIdPosicao_Pistao_Avanco;
 extern const CStringDictionary::TStringId g_nStringIdPosicao_Pistao_Recuo;
 extern const CStringDictionary::TStringId g_nStringIdPosicao_Rotativo_Avanco;
 extern const CStringDictionary::TStringId g_nStringIdPosicao_Rotativo_Recuo;
 extern const CStringDictionary::TStringId g_nStringIdTem_peca;
 extern const CStringDictionary::TStringId g_nStringIdUPDT;

